[project]
name = "faststream-fastapi-taskiq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.114.1",
    "faststream>=0.5.23",
    "pydantic-settings>=2.5.2",
    "taskiq-faststream[nats]>=0.2.0",
]
